# Site settings
baseurl = "https://yuanfan.vercel.app/"
languageCode = "en"
title = "earfanfan | 袁凡"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
paginate = 9

[params]
	author = "袁凡"
	description = "YuanFan's Blog"
	bio = "一天是永恒的缩影，逆水行舟，不进则退"

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = true
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = '8f70ac927bdcaf45a22df60dd240bfcd'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "主页"
	about = "关于"
	archive = "博客"
	subscribe = "订阅"
	Tags = "归档"

	olderPosts = "前面的狗"
	newerPosts = "后面的猫"
	copyright = ""

	# show latest posts in single page
	showLatestPosts = true
	readMore = "下一篇&上一篇"

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "阿木狗主云游天外了"
	subtitle404 = "天灵灵，地灵灵，时灵时不灵"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com"
	twitter-square = "https://www.twitter.com"
	github-square = "https://www.github.com/earfanfan"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "earfanfan/BlogComments" 
  issueTerm = "pathname"
  theme = "github-light"
  
[markup]
    [markup.goldmark.renderer]
      unsafe = true  
